spring:
  profiles:
    active:
    - dev
---
server:
  port: 8811
spring:
  profiles: dev
  application:
    name: springcloud-config-client
eureka:
  client:
    service-url:
      defaultZone: http://springcloudEureka7001:7001/eureka
---
server:
  port: 8822
spring:
  profiles: test
  application:
    name: springcloud-config-client
eureka:
  client:
    service-url:
      defaultZone: http://springcloudEureka7001:7001/eureka/