spring:
  profiles:
    active: 
    - dev
---
server:
  port: 8001
  
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: org.example.springcloud.domain    # 所有domain别名类所在包
  mapper-locations:
  - classpath:mybatis/mapper/*.xml                       # mapper映射文件
    
spring:
  profiles: dev
  application:
    name: springcloud-config-provider
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    url: jdbc:mysql://localhost:3306/cloudDB01              # 数据库名称
    username: root
    password: root
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200                                  # 等待连接获取的最大超时时间
      
eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      #defaultZone: http://localhost:7001/eureka
      defaultZone: http://springcloudEureka7001:7001/eureka/,http://springcloudEureka7002:7002/eureka/,http://springcloudEureka7003:7003/eureka/
  instance:
    instance-id: springcloud-provider8001
    prefer-ip-address: true     #访问路径可以显示IP地址

info:
  app.name: org-springcloud
  company.name: www.springcloud.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$

---
server:
  port: 8001
  
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: org.example.springcloud.domain    # 所有domain别名类所在包
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml                       # mapper映射文件
    
spring: 
   profiles: test
   application:
    name: springcloud-config-provider
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    url: jdbc:mysql://localhost:3306/cloudDB01              # 数据库名称
    username: root
    password: root
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200                                  # 等待连接获取的最大超时时间
      
eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      #defaultZone: http://localhost:7001/eureka
      defaultZone: http://springcloudEureka7001:7001/eureka/,http://springcloudEureka7002:7002/eureka/,http://springcloudEureka7003:7003/eureka/
  instance:
    instance-id: springcloud-provider8001
    prefer-ip-address: true     #访问路径可以显示IP地址

info:
  app.name: org-springcloud
  company.name: www.springcloud.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$